auterion-api-version: 7
auterion-app-base: none
app-name: zerotier-vpn
app-author: com.yourcompany.zerotier-vpn
app-version: 1.0.0
target-platform: skynode-s

services:
  zerotier:
    build: services/zerotier

compose-override:
  services:
    zerotier:
      cap_add:
        - NET_ADMIN
        - SYS_ADMIN
      devices:
        - /dev/net/tun:/dev/net/tun
      network_mode: host
      volumes:
        - zerotier-data:/var/lib/zerotier-one
      restart: unless-stopped

  volumes:
    zerotier-data:
